### ISSUE TITLE
Can you please create a LICENSE file?

### ISSUE THREAD

**Issue by jayavanth** [Trrnts/Trrnts#8]
I'm using it in an open-source project. It would be great if you could add a LICENSE. Instructions here: https://help.github.com/en/github/building-a-strong-community/adding-a-license-to-a-repository

**Comment by jayavanth** [comment]
Without a license file, no one can use this code. For more details: https://github.com/organicinternet/magento-configurable-simple/issues/222#issuecomment-135201411

**Comment by mmathys** [comment]
just use it man
